// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/pkg/proto/chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型
type MessageType int32

const (
	MessageType_TEXT   MessageType = 0
	MessageType_SYSTEM MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "SYSTEM",
	}
	MessageType_value = map[string]int32{
		"TEXT":   0,
		"SYSTEM": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_proto_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_pkg_proto_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_pkg_proto_chat_proto_rawDescGZIP(), []int{0}
}

// WebSocket 消息
type WSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId       string                 `protobuf:"bytes,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	SeqId         int64                  `protobuf:"varint,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          MessageType            `protobuf:"varint,7,opt,name=type,proto3,enum=chat.MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_internal_pkg_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WSMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WSMessage) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *WSMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WSMessage) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *WSMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WSMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

// 历史消息请求
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	LastSeqId     int64                  `protobuf:"varint,2,opt,name=last_seq_id,json=lastSeqId,proto3" json:"last_seq_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_internal_pkg_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *HistoryRequest) GetLastSeqId() int64 {
	if x != nil {
		return x.LastSeqId
	}
	return 0
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 历史消息响应
type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*WSMessage           `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_internal_pkg_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryResponse) GetMessages() []*WSMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *HistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_internal_pkg_proto_chat_proto protoreflect.FileDescriptor

const file_internal_pkg_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/pkg/proto/chat.proto\x12\x04chat\"\xd4\x01\n" +
	"\tWSMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bguild_id\x18\x03 \x01(\tR\aguildId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x15\n" +
	"\x06seq_id\x18\x05 \x01(\x03R\x05seqId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12%\n" +
	"\x04type\x18\a \x01(\x0e2\x11.chat.MessageTypeR\x04type\"a\n" +
	"\x0eHistoryRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x1e\n" +
	"\vlast_seq_id\x18\x02 \x01(\x03R\tlastSeqId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"Y\n" +
	"\x0fHistoryResponse\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.chat.WSMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore*#\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01B&Z$github.com/Gopher0727/ChatRoom/protob\x06proto3"

var (
	file_internal_pkg_proto_chat_proto_rawDescOnce sync.Once
	file_internal_pkg_proto_chat_proto_rawDescData []byte
)

func file_internal_pkg_proto_chat_proto_rawDescGZIP() []byte {
	file_internal_pkg_proto_chat_proto_rawDescOnce.Do(func() {
		file_internal_pkg_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_chat_proto_rawDesc), len(file_internal_pkg_proto_chat_proto_rawDesc)))
	})
	return file_internal_pkg_proto_chat_proto_rawDescData
}

var file_internal_pkg_proto_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pkg_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_pkg_proto_chat_proto_goTypes = []any{
	(MessageType)(0),        // 0: chat.MessageType
	(*WSMessage)(nil),       // 1: chat.WSMessage
	(*HistoryRequest)(nil),  // 2: chat.HistoryRequest
	(*HistoryResponse)(nil), // 3: chat.HistoryResponse
}
var file_internal_pkg_proto_chat_proto_depIdxs = []int32{
	0, // 0: chat.WSMessage.type:type_name -> chat.MessageType
	1, // 1: chat.HistoryResponse.messages:type_name -> chat.WSMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pkg_proto_chat_proto_init() }
func file_internal_pkg_proto_chat_proto_init() {
	if File_internal_pkg_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_chat_proto_rawDesc), len(file_internal_pkg_proto_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pkg_proto_chat_proto_goTypes,
		DependencyIndexes: file_internal_pkg_proto_chat_proto_depIdxs,
		EnumInfos:         file_internal_pkg_proto_chat_proto_enumTypes,
		MessageInfos:      file_internal_pkg_proto_chat_proto_msgTypes,
	}.Build()
	File_internal_pkg_proto_chat_proto = out.File
	file_internal_pkg_proto_chat_proto_goTypes = nil
	file_internal_pkg_proto_chat_proto_depIdxs = nil
}
