// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/pkg/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       *WSMessage             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageRequest) Reset() {
	*x = PushMessageRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageRequest) ProtoMessage() {}

func (x *PushMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageRequest.ProtoReflect.Descriptor instead.
func (*PushMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushMessageRequest) GetMessage() *WSMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type PushMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageResponse) Reset() {
	*x = PushMessageResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResponse) ProtoMessage() {}

func (x *PushMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResponse.ProtoReflect.Descriptor instead.
func (*PushMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BroadcastRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GuildId        string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Message        *WSMessage             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExcludeUserIds []string               `protobuf:"bytes,3,rep,name=exclude_user_ids,json=excludeUserIds,proto3" json:"exclude_user_ids,omitempty"` // 排除的用户ID列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *BroadcastRequest) GetMessage() *WSMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BroadcastRequest) GetExcludeUserIds() []string {
	if x != nil {
		return x.ExcludeUserIds
	}
	return nil
}

type BroadcastResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeliveredCount int32                  `protobuf:"varint,1,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"` // 成功推送的用户数
	FailedUserIds  []string               `protobuf:"bytes,2,rep,name=failed_user_ids,json=failedUserIds,proto3" json:"failed_user_ids,omitempty"`   // 推送失败的用户ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastResponse) GetDeliveredCount() int32 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

func (x *BroadcastResponse) GetFailedUserIds() []string {
	if x != nil {
		return x.FailedUserIds
	}
	return nil
}

type UserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusRequest) Reset() {
	*x = UserStatusRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusRequest) ProtoMessage() {}

func (x *UserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusRequest.ProtoReflect.Descriptor instead.
func (*UserStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	GatewayNode   string                 `protobuf:"bytes,2,opt,name=gateway_node,json=gatewayNode,proto3" json:"gateway_node,omitempty"` // 用户连接的 Gateway 节点地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *UserStatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *UserStatusResponse) GetGatewayNode() string {
	if x != nil {
		return x.GatewayNode
	}
	return ""
}

type NodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoRequest) Reset() {
	*x = NodeInfoRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoRequest) ProtoMessage() {}

func (x *NodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoRequest.ProtoReflect.Descriptor instead.
func (*NodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{6}
}

type NodeInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address         string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ConnectionCount int32                  `protobuf:"varint,3,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeInfoResponse) Reset() {
	*x = NodeInfoResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoResponse) ProtoMessage() {}

func (x *NodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoResponse.ProtoReflect.Descriptor instead.
func (*NodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *NodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfoResponse) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *NodeInfoResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{8}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId       string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=chat.MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendMessageRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *WSMessage             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *SendMessageResponse) GetMessage() *WSMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchGetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []string               `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMessagesRequest) Reset() {
	*x = BatchGetMessagesRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMessagesRequest) ProtoMessage() {}

func (x *BatchGetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMessagesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetMessagesRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type BatchGetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*WSMessage           `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMessagesResponse) Reset() {
	*x = BatchGetMessagesResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMessagesResponse) ProtoMessage() {}

func (x *BatchGetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMessagesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetMessagesResponse) GetMessages() []*WSMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	HubId         string                 `protobuf:"bytes,3,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *GetUserResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type BatchGetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersRequest) Reset() {
	*x = BatchGetUsersRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersRequest) ProtoMessage() {}

func (x *BatchGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *BatchGetUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type BatchGetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GetUserResponse     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersResponse) Reset() {
	*x = BatchGetUsersResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersResponse) ProtoMessage() {}

func (x *BatchGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetUsersResponse) GetUsers() []*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	GatewayNode   string                 `protobuf:"bytes,3,opt,name=gateway_node,json=gatewayNode,proto3" json:"gateway_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusRequest) Reset() {
	*x = UpdateUserStatusRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusRequest) ProtoMessage() {}

func (x *UpdateUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateUserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserStatusRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *UpdateUserStatusRequest) GetGatewayNode() string {
	if x != nil {
		return x.GatewayNode
	}
	return ""
}

type UpdateUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusResponse) Reset() {
	*x = UpdateUserStatusResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusResponse) ProtoMessage() {}

func (x *UpdateUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateUserStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetGuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildRequest) Reset() {
	*x = GetGuildRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildRequest) ProtoMessage() {}

func (x *GetGuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildRequest.ProtoReflect.Descriptor instead.
func (*GetGuildRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetGuildRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type GetGuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	InviteCode    string                 `protobuf:"bytes,4,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildResponse) Reset() {
	*x = GetGuildResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildResponse) ProtoMessage() {}

func (x *GetGuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildResponse.ProtoReflect.Descriptor instead.
func (*GetGuildResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetGuildResponse) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *GetGuildResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGuildResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetGuildResponse) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *GetGuildResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetGuildMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildMembersRequest) Reset() {
	*x = GetGuildMembersRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildMembersRequest) ProtoMessage() {}

func (x *GetGuildMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildMembersRequest.ProtoReflect.Descriptor instead.
func (*GetGuildMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetGuildMembersRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *GetGuildMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGuildMembersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetGuildMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildMembersResponse) Reset() {
	*x = GetGuildMembersResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildMembersResponse) ProtoMessage() {}

func (x *GetGuildMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildMembersResponse.ProtoReflect.Descriptor instead.
func (*GetGuildMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetGuildMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetGuildMembersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CheckMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId       string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMembershipRequest) Reset() {
	*x = CheckMembershipRequest{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMembershipRequest) ProtoMessage() {}

func (x *CheckMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMembershipRequest.ProtoReflect.Descriptor instead.
func (*CheckMembershipRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{24}
}

func (x *CheckMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckMembershipRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type CheckMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMembershipResponse) Reset() {
	*x = CheckMembershipResponse{}
	mi := &file_internal_pkg_proto_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMembershipResponse) ProtoMessage() {}

func (x *CheckMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMembershipResponse.ProtoReflect.Descriptor instead.
func (*CheckMembershipResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_service_proto_rawDescGZIP(), []int{25}
}

func (x *CheckMembershipResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *CheckMembershipResponse) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

var File_internal_pkg_proto_service_proto protoreflect.FileDescriptor

const file_internal_pkg_proto_service_proto_rawDesc = "" +
	"\n" +
	" internal/pkg/proto/service.proto\x12\x04chat\x1a\x1dinternal/pkg/proto/chat.proto\"X\n" +
	"\x12PushMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\amessage\x18\x02 \x01(\v2\x0f.chat.WSMessageR\amessage\"E\n" +
	"\x13PushMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x82\x01\n" +
	"\x10BroadcastRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12)\n" +
	"\amessage\x18\x02 \x01(\v2\x0f.chat.WSMessageR\amessage\x12(\n" +
	"\x10exclude_user_ids\x18\x03 \x03(\tR\x0eexcludeUserIds\"d\n" +
	"\x11BroadcastResponse\x12'\n" +
	"\x0fdelivered_count\x18\x01 \x01(\x05R\x0edeliveredCount\x12&\n" +
	"\x0ffailed_user_ids\x18\x02 \x03(\tR\rfailedUserIds\",\n" +
	"\x11UserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\x12UserStatusResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12!\n" +
	"\fgateway_node\x18\x02 \x01(\tR\vgatewayNode\"\x11\n" +
	"\x0fNodeInfoRequest\"\x97\x01\n" +
	"\x10NodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12)\n" +
	"\x10connection_count\x18\x03 \x01(\x05R\x0fconnectionCount\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x89\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.chat.MessageTypeR\x04type\"V\n" +
	"\x13SendMessageResponse\x12)\n" +
	"\amessage\x18\x01 \x01(\v2\x0f.chat.WSMessageR\amessage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\x17BatchGetMessagesRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\tR\n" +
	"messageIds\"G\n" +
	"\x18BatchGetMessagesResponse\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.chat.WSMessageR\bmessages\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"|\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x15\n" +
	"\x06hub_id\x18\x03 \x01(\tR\x05hubId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"1\n" +
	"\x14BatchGetUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"D\n" +
	"\x15BatchGetUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.chat.GetUserResponseR\x05users\"m\n" +
	"\x17UpdateUserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12!\n" +
	"\fgateway_node\x18\x03 \x01(\tR\vgatewayNode\"4\n" +
	"\x18UpdateUserStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x0fGetGuildRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"\x9c\x01\n" +
	"\x10GetGuildResponse\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1f\n" +
	"\vinvite_code\x18\x04 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"a\n" +
	"\x16GetGuildMembersRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"U\n" +
	"\x17GetGuildMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"L\n" +
	"\x16CheckMembershipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\"S\n" +
	"\x17CheckMembershipResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x1b\n" +
	"\tjoined_at\x18\x02 \x01(\x03R\bjoinedAt2\xe1\x02\n" +
	"\x0eGatewayService\x12B\n" +
	"\vPushMessage\x12\x18.chat.PushMessageRequest\x1a\x19.chat.PushMessageResponse\x12C\n" +
	"\x10BroadcastToGuild\x12\x16.chat.BroadcastRequest\x1a\x17.chat.BroadcastResponse\x12D\n" +
	"\x0fCheckUserOnline\x12\x17.chat.UserStatusRequest\x1a\x18.chat.UserStatusResponse\x12<\n" +
	"\vGetNodeInfo\x12\x15.chat.NodeInfoRequest\x1a\x16.chat.NodeInfoResponse\x12B\n" +
	"\vHealthCheck\x12\x18.chat.HealthCheckRequest\x1a\x19.chat.HealthCheckResponse2\xe2\x01\n" +
	"\x0eMessageService\x12B\n" +
	"\vSendMessage\x12\x18.chat.SendMessageRequest\x1a\x19.chat.SendMessageResponse\x129\n" +
	"\n" +
	"GetHistory\x12\x14.chat.HistoryRequest\x1a\x15.chat.HistoryResponse\x12Q\n" +
	"\x10BatchGetMessages\x12\x1d.chat.BatchGetMessagesRequest\x1a\x1e.chat.BatchGetMessagesResponse2\xe2\x01\n" +
	"\vUserService\x126\n" +
	"\aGetUser\x12\x14.chat.GetUserRequest\x1a\x15.chat.GetUserResponse\x12H\n" +
	"\rBatchGetUsers\x12\x1a.chat.BatchGetUsersRequest\x1a\x1b.chat.BatchGetUsersResponse\x12Q\n" +
	"\x10UpdateUserStatus\x12\x1d.chat.UpdateUserStatusRequest\x1a\x1e.chat.UpdateUserStatusResponse2\xe9\x01\n" +
	"\fGuildService\x129\n" +
	"\bGetGuild\x12\x15.chat.GetGuildRequest\x1a\x16.chat.GetGuildResponse\x12N\n" +
	"\x0fGetGuildMembers\x12\x1c.chat.GetGuildMembersRequest\x1a\x1d.chat.GetGuildMembersResponse\x12N\n" +
	"\x0fCheckMembership\x12\x1c.chat.CheckMembershipRequest\x1a\x1d.chat.CheckMembershipResponseB&Z$github.com/Gopher0727/ChatRoom/protob\x06proto3"

var (
	file_internal_pkg_proto_service_proto_rawDescOnce sync.Once
	file_internal_pkg_proto_service_proto_rawDescData []byte
)

func file_internal_pkg_proto_service_proto_rawDescGZIP() []byte {
	file_internal_pkg_proto_service_proto_rawDescOnce.Do(func() {
		file_internal_pkg_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_service_proto_rawDesc), len(file_internal_pkg_proto_service_proto_rawDesc)))
	})
	return file_internal_pkg_proto_service_proto_rawDescData
}

var file_internal_pkg_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_pkg_proto_service_proto_goTypes = []any{
	(*PushMessageRequest)(nil),       // 0: chat.PushMessageRequest
	(*PushMessageResponse)(nil),      // 1: chat.PushMessageResponse
	(*BroadcastRequest)(nil),         // 2: chat.BroadcastRequest
	(*BroadcastResponse)(nil),        // 3: chat.BroadcastResponse
	(*UserStatusRequest)(nil),        // 4: chat.UserStatusRequest
	(*UserStatusResponse)(nil),       // 5: chat.UserStatusResponse
	(*NodeInfoRequest)(nil),          // 6: chat.NodeInfoRequest
	(*NodeInfoResponse)(nil),         // 7: chat.NodeInfoResponse
	(*HealthCheckRequest)(nil),       // 8: chat.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 9: chat.HealthCheckResponse
	(*SendMessageRequest)(nil),       // 10: chat.SendMessageRequest
	(*SendMessageResponse)(nil),      // 11: chat.SendMessageResponse
	(*BatchGetMessagesRequest)(nil),  // 12: chat.BatchGetMessagesRequest
	(*BatchGetMessagesResponse)(nil), // 13: chat.BatchGetMessagesResponse
	(*GetUserRequest)(nil),           // 14: chat.GetUserRequest
	(*GetUserResponse)(nil),          // 15: chat.GetUserResponse
	(*BatchGetUsersRequest)(nil),     // 16: chat.BatchGetUsersRequest
	(*BatchGetUsersResponse)(nil),    // 17: chat.BatchGetUsersResponse
	(*UpdateUserStatusRequest)(nil),  // 18: chat.UpdateUserStatusRequest
	(*UpdateUserStatusResponse)(nil), // 19: chat.UpdateUserStatusResponse
	(*GetGuildRequest)(nil),          // 20: chat.GetGuildRequest
	(*GetGuildResponse)(nil),         // 21: chat.GetGuildResponse
	(*GetGuildMembersRequest)(nil),   // 22: chat.GetGuildMembersRequest
	(*GetGuildMembersResponse)(nil),  // 23: chat.GetGuildMembersResponse
	(*CheckMembershipRequest)(nil),   // 24: chat.CheckMembershipRequest
	(*CheckMembershipResponse)(nil),  // 25: chat.CheckMembershipResponse
	(*WSMessage)(nil),                // 26: chat.WSMessage
	(MessageType)(0),                 // 27: chat.MessageType
	(*HistoryRequest)(nil),           // 28: chat.HistoryRequest
	(*HistoryResponse)(nil),          // 29: chat.HistoryResponse
}
var file_internal_pkg_proto_service_proto_depIdxs = []int32{
	26, // 0: chat.PushMessageRequest.message:type_name -> chat.WSMessage
	26, // 1: chat.BroadcastRequest.message:type_name -> chat.WSMessage
	27, // 2: chat.SendMessageRequest.type:type_name -> chat.MessageType
	26, // 3: chat.SendMessageResponse.message:type_name -> chat.WSMessage
	26, // 4: chat.BatchGetMessagesResponse.messages:type_name -> chat.WSMessage
	15, // 5: chat.BatchGetUsersResponse.users:type_name -> chat.GetUserResponse
	0,  // 6: chat.GatewayService.PushMessage:input_type -> chat.PushMessageRequest
	2,  // 7: chat.GatewayService.BroadcastToGuild:input_type -> chat.BroadcastRequest
	4,  // 8: chat.GatewayService.CheckUserOnline:input_type -> chat.UserStatusRequest
	6,  // 9: chat.GatewayService.GetNodeInfo:input_type -> chat.NodeInfoRequest
	8,  // 10: chat.GatewayService.HealthCheck:input_type -> chat.HealthCheckRequest
	10, // 11: chat.MessageService.SendMessage:input_type -> chat.SendMessageRequest
	28, // 12: chat.MessageService.GetHistory:input_type -> chat.HistoryRequest
	12, // 13: chat.MessageService.BatchGetMessages:input_type -> chat.BatchGetMessagesRequest
	14, // 14: chat.UserService.GetUser:input_type -> chat.GetUserRequest
	16, // 15: chat.UserService.BatchGetUsers:input_type -> chat.BatchGetUsersRequest
	18, // 16: chat.UserService.UpdateUserStatus:input_type -> chat.UpdateUserStatusRequest
	20, // 17: chat.GuildService.GetGuild:input_type -> chat.GetGuildRequest
	22, // 18: chat.GuildService.GetGuildMembers:input_type -> chat.GetGuildMembersRequest
	24, // 19: chat.GuildService.CheckMembership:input_type -> chat.CheckMembershipRequest
	1,  // 20: chat.GatewayService.PushMessage:output_type -> chat.PushMessageResponse
	3,  // 21: chat.GatewayService.BroadcastToGuild:output_type -> chat.BroadcastResponse
	5,  // 22: chat.GatewayService.CheckUserOnline:output_type -> chat.UserStatusResponse
	7,  // 23: chat.GatewayService.GetNodeInfo:output_type -> chat.NodeInfoResponse
	9,  // 24: chat.GatewayService.HealthCheck:output_type -> chat.HealthCheckResponse
	11, // 25: chat.MessageService.SendMessage:output_type -> chat.SendMessageResponse
	29, // 26: chat.MessageService.GetHistory:output_type -> chat.HistoryResponse
	13, // 27: chat.MessageService.BatchGetMessages:output_type -> chat.BatchGetMessagesResponse
	15, // 28: chat.UserService.GetUser:output_type -> chat.GetUserResponse
	17, // 29: chat.UserService.BatchGetUsers:output_type -> chat.BatchGetUsersResponse
	19, // 30: chat.UserService.UpdateUserStatus:output_type -> chat.UpdateUserStatusResponse
	21, // 31: chat.GuildService.GetGuild:output_type -> chat.GetGuildResponse
	23, // 32: chat.GuildService.GetGuildMembers:output_type -> chat.GetGuildMembersResponse
	25, // 33: chat.GuildService.CheckMembership:output_type -> chat.CheckMembershipResponse
	20, // [20:34] is the sub-list for method output_type
	6,  // [6:20] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_pkg_proto_service_proto_init() }
func file_internal_pkg_proto_service_proto_init() {
	if File_internal_pkg_proto_service_proto != nil {
		return
	}
	file_internal_pkg_proto_chat_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_service_proto_rawDesc), len(file_internal_pkg_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_internal_pkg_proto_service_proto_goTypes,
		DependencyIndexes: file_internal_pkg_proto_service_proto_depIdxs,
		MessageInfos:      file_internal_pkg_proto_service_proto_msgTypes,
	}.Build()
	File_internal_pkg_proto_service_proto = out.File
	file_internal_pkg_proto_service_proto_goTypes = nil
	file_internal_pkg_proto_service_proto_depIdxs = nil
}
